# Generated by Django 5.2.11 on 2026-02-16 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herb_type', models.CharField(choices=[('Ashwagandha', 'Ashwagandha'), ('Tulsi', 'Tulsi')], max_length=100)),
                ('harvest_date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(upload_to='batches/')),
                ('authenticity_score', models.FloatField(blank=True, null=True)),
                ('geo_valid', models.BooleanField(blank=True, null=True)),
                ('potency_score', models.FloatField(blank=True, null=True)),
                ('compliance_status', models.CharField(blank=True, max_length=50, null=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
