# Generated by Django 5.2.11 on 2026-02-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='farmer',
        ),
        migrations.AddField(
            model_name='batch',
            name='farmer_id',
            field=models.CharField(default='unknown', help_text='Supabase user ID', max_length=255),
        ),
    ]
